name: Build sjpp and run unit tests

on: [push]

jobs:
  Compile_and_run_tests:
    runs-on: ubuntu-latest
    env:
      path: build
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libcurlpp-dev doxygen
      - name: Create build directory
        run: mkdir ${{ env.path }}
      - name: Compile
        working-directory: ${{ env.path }}
        run: |
          cmake ..
          make
      - name: Run tests
        working-directory: ${{ env.path }}
        run: ctest -V
